#!/bin/bash

if ! (pacman -Q netcat >/dev/null) ; then
  echo "Netcat must be installed to use this script."
  echo "Please install now with 'sudo pacman -S netcat'"
  exit 1
fi


if ! (nc -zw1 google.com 443); then
  echo "You are not connected to the internet."
  exit 1
fi

if ! (rclone listremotes >/dev/null); then
  echo "You need to setup an rclone remote."
  echo "Do this now with 'rclone config'"
  echo "Make sure to call the remote 'GoogleDrive'"
  exit 1
fi

echo "[INFO] STARTING SYNC"
if (rclone sync GoogleDrive: ~/GoogleDrive -v); then
  echo ""
  echo "[INFO] SYNC COMPLETE"
fi
